packages:
  - packages/**
  - '!packages/common'
  - '!**/_tdesign*/**'
  - '!**/uni_modules/**'
catalog:
  '@babel/core': ^7.26.0
  '@babel/helper-module-imports': 7.22.5
  '@babel/plugin-proposal-class-properties': ^7.14.5
  '@babel/plugin-proposal-decorators': ^7.18.9
  '@babel/plugin-transform-class-properties': ^7.22.3
  '@babel/plugin-transform-runtime': ^7.16.4
  '@babel/preset-env': ^7.12.11
  '@babel/preset-typescript': ^7.26.0
  '@babel/runtime': ^7.16.5
  '@commitlint/cli': ^16.3.0
  '@commitlint/config-conventional': ^16.2.4
  '@plugin-light/vite-plugin-gen-version': ^1.0.1
  '@popperjs/core': ^2.11.8
  '@rollup/plugin-babel': ^5.2.2
  '@rollup/plugin-commonjs': ^21.0.1
  '@rollup/plugin-eslint': ^8.0.1
  '@rollup/plugin-json': ^4.1.0
  '@rollup/plugin-node-resolve': ^13.3.0
  '@rollup/plugin-replace': ^2.3.4
  '@rollup/plugin-url': ^6.0.0
  '@soerenmartius/vue3-clipboard': ^0.1.1
  '@stylistic/eslint-plugin-jsx': 3.1.0
  '@types/jest': ^27.0.3
  '@types/lodash-es': ^4.17.12
  '@types/node': ^20.17.2
  '@types/prismjs': ^1.26.5
  '@types/tinycolor2': ^1.4.6
  '@types/validator': ^13.6.3
  '@typescript-eslint/eslint-plugin': ^5.62.0
  '@typescript-eslint/experimental-utils': ^2.24.0
  '@typescript-eslint/parser': ~5.35.1
  '@typescript-eslint/typescript-estree': ^8.8.0
  '@use-gesture/vanilla': ^10.3.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vue/babel-plugin-jsx': 1.1.1
  '@vue/compiler-sfc': ^3.2.4
  '@vue/eslint-config-typescript': ^9.1.0
  '@vue/runtime-core': ^3.5.21
  '@vue/shared': 3.3.8
  '@vue/test-utils': 2.4.1
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': 10.7.0
  autoprefixer: ^10.2.4
  babel-jest: ^26.6.3
  camelcase: ~6.3.0
  chokidar: ^4.0.3
  commitizen: ^4.3.1
  commitlint: ^17.0.3
  concurrently: ^9.2.1
  conventional-changelog-cli: ^2.1.1
  cos-nodejs-sdk-v5: ^2.15.4
  cross-env: ^7.0.3
  cz-conventional-changelog: ^3.3.0
  dayjs: ^1.11.13
  debug: ^4.3.1
  del: ^6.1.1
  dom-parser: ^0.1.6
  dotenv: ^17.2.3
  echarts: ^6.0.0
  esbuild: ^0.14.3
  eslint: ^8.57.1
  eslint-config-airbnb-base: ^14.2.1
  eslint-config-prettier: ^6.15.0
  eslint-import-resolver-alias: 1.1.2
  eslint-import-resolver-node: 0.3.9
  eslint-plugin-import: ^2.31.0
  eslint-plugin-jest: '25'
  eslint-plugin-prettier: ^4.2.1
  eslint-plugin-react: 7.26.1
  eslint-plugin-react-hooks: 4.2.0
  eslint-plugin-tailwindcss: 3.18.0
  eslint-plugin-vue: 9.14.0
  get-intrinsic: 1.3.0
  glob: ^10.4.4
  gray-matter: ^4.0.3
  gulp: ^4.0.2
  gulp-changed: ^4.0.2
  gulp-clean-css: ^4.3.0
  gulp-htmlmin: ^5.0.1
  gulp-if: ^3.0.0
  gulp-insert: ^0.5.0
  gulp-jsonminify: ^1.1.0
  gulp-less: ^5.0.0
  gulp-mp-npm: ^1.9.7
  gulp-plumber: ^1.2.1
  gulp-rename: ^2.0.0
  gulp-replace: ^1.0.0
  gulp-replace-task: ^2.0.1
  gulp-sourcemaps: ^3.0.0
  gulp-terser: ^2.1.0
  gulp-typescript: ^6.0.0-alpha.1
  gulp-watch: ^5.0.1
  husky: ^9.1.7
  jest: ^26.6.3
  jest-html-reporter: ^3.10.2
  jsdom: ^20.0.0
  less: ^4.5.1
  lint-staged: ^10.5.4
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  lodash.camelcase: ^4.3.0
  lodash.upperfirst: ^4.3.1
  marked: ^16.1.2
  merge2: ^1.4.1
  min-indent: ^1.0.1
  mitt: ^3.0.0
  mockdate: ^3.0.5
  npm-run-all2: ^8.0.4
  playwright: ^1.19.1
  postcss: ^8.5.6
  postcss-less: ^6.0.0
  postcss-rpx-transform: ^1.0.1
  prettier: ^3.8.1
  prismjs: ^1.30.0
  qrcode.vue: ^3.2.2
  regenerator-runtime: ^0.13.9
  rimraf: ^5.0.7
  rollup: ^2.47.0
  rollup-plugin-analyzer: ^3.3.0
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-delete: ^2.0.0
  rollup-plugin-esbuild: ^4.5.0
  rollup-plugin-ignore-import: ^1.3.2
  rollup-plugin-multi-input: 1.1.1
  rollup-plugin-postcss: ^4.0.0
  rollup-plugin-static-import: ^1.0.0
  rollup-plugin-styles: ^3.14.1
  rollup-plugin-terser: ^7.0.2
  rollup-plugin-vue: ^6.0.0
  rollup-pluginutils: ^2.8.2
  sass: ^1.90.0
  standard-changelog: ^2.0.27
  stylelint: ^13.13.1
  stylelint-config-common: 1.0.10
  stylelint-config-standard: ^39.0.1
  stylelint-less: ^3.0.1
  stylelint-scss: 6.10.0
  t-comm: ^2.0.26
  tdesign-uniapp-auto-import-resolver: 0.1.3
  tinycolor2: ^1.6.0
  tslib: ^2.8.1
  typescript: ~4.7.4
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^29.2.0
  validator: ^13.5.1
  vite: ^6.3.5
  vite-plugin-tdoc: ^2.0.1
  vitest: ^3.2.4
  vue: ^3.5.20
  vue-eslint-parser: ^8.0.1
  vue-i18n: ^9.1.9
  vue-router: ^4.4.5
  vue-tsc: ^1.8.27
  zrender: ^6.0.0
catalogMode: prefer
catalogs:
  miniprogram:
    miniprogram-api-typings: ^3.12.3
    miniprogram-automator: ^0.10.0
    miniprogram-computed: ^5.0.0
    miniprogram-simulate: ^1.6.0
  tdesign:
    '@tdesign/site-components': ^0.18.0
    '@tdesign/theme-generator': ^1.2.1
    tdesign-icons-view: ^0.5.1
    tdesign-icons-vue-next: ^0.4.2
    tdesign-publish-cli: ^0.0.12
  uni:
    '@dcloudio/types': ^3.4.28
    '@dcloudio/uni-app': 3.0.0-4030620241128001
    '@dcloudio/uni-app-harmony': 3.0.0-4030620241128001
    '@dcloudio/uni-app-plus': 3.0.0-4030620241128001
    '@dcloudio/uni-automator': 3.0.0-4030620241128001
    '@dcloudio/uni-cli-shared': 3.0.0-4030620241128001
    '@dcloudio/uni-components': 3.0.0-4030620241128001
    '@dcloudio/uni-h5': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-alipay': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-baidu': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-compiler': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-jd': 3.0.0-4080720251210001
    '@dcloudio/uni-mp-kuaishou': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-lark': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-qq': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-toutiao': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-weixin': 3.0.0-4030620241128001
    '@dcloudio/uni-mp-xhs': 3.0.0-4030620241128001
    '@dcloudio/uni-quickapp-webview': 3.0.0-4030620241128001
    '@dcloudio/uni-stacktracey': 3.0.0-4030620241128001
    '@dcloudio/vite-plugin-uni': 3.0.0-4030620241128001
shamefullyHoist: true
