name: 'Install Dependencies'

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: '14'

runs:
  using: "composite"
  steps: 
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
    - run: npm install
      shell: bash