name: 'Install Dependencies'

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: '14'

runs:
  using: "composite"
  steps: 
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
      shell: bash