# force copy from tencent/tdesign
name: Issue Add Assigness

on:
  issues:
    types: [opened]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/workflows/actions/issues-helper@main
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 @{{ github.event.issue.user.login }}，感谢给 TDesign 提出了 issue。
            请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。
