name: Issue Help wanted

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'help wanted'
    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comment } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '任何人都可以处理此问题。\n**请务必在您的 `pull request` 中引用此问题。** :sparkles:\n感谢你的贡献! :sparkles:'
            });
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
              content: 'heart'
            });
