name: Issue Help wanted

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'help wanted'
    steps:
      - name: Add comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            任何人都可以处理此问题。
            **请务必在您的 `pull request` 中引用此问题。** :sparkles: 
            感谢你的贡献! :sparkles:
          emoji: 'heart'
